---
- name: python-setuptools is installed
  yum:
    name: python-setuptools
    state: installed

- name: python bindings are installed
  easy_install:
    name: firewall
    state: present

- name: is installed
  yum:
    name: firewalld
    state: installed

- name: interface to Internet is in public zone
  firewalld:
    zone: public
    interface: enp0s3
    permanent: true
    state: enabled
  notify:
    - reload firewall

- name: port rules are configured
  firewalld:
    port: "{{item.value.port}}"
    zone: "{{item.value.zone}}"
    permanent: true
    state: "{{item.value.state}}"
  with_dict: "{{firewall_port_rules}}"
  notify:
    - reload firewall

- name: is enabled and running
  service:
    name: firewalld
    state: running
    enabled: yes
