---
- name: python-setuptools is installed
  yum: name=python-setuptools state=installed
  tags: [firewall, install]

- name: python bindings are installed
  easy_install: name=firewall state=present
  tags: [firewall, install]

- name: is installed
  yum: name=firewalld state=installed
  tags: [firewall, install]

- name: is enabled
  service: name=firewalld enabled=yes
  tags: [firewall, install]

- name: interface to Internet is in public zone
  firewalld: zone=public interface={{public_interface}} permanent=true state=enabled
  notify:
    - reload firewall
  tags: [firewall, configure]

- name: port 22/tcp is open in public zone
  firewalld: zone=public port=22/tcp state=enabled permanent=true
  notify:
    - reload firewall
  tags: [firewall, configure]

- name: is running
  service: name=firewalld state=running enabled=yes
  tags: [firewall, check]
