---
- name: EPEL repository is present
  yum:
    name: epel-release
    state: present

- name: EPEL GPG key is imported
  rpm_key:
    key: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    state: present

- name: munin-node is installed
  yum:
    name: munin-node
    state: installed

- name: munin-node configuration is installed
  template:
    src: munin-node.conf.j2
    dest: /etc/munin/munin-node.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart munin-node

- name: munin-node is enabled and running
  service:
    name: munin-node
    state: running
    enabled: yes

- name: create munin 3rd party plugin directory
  file:
    path: /usr/local/munin/lib/plugins
    owner: root
    group: root
    mode: 0755
    state: directory
    recurse: yes

- name: munin yum script is installed
  copy:
    src: yum
    dest: /usr/local/munin/lib/plugins
    owner: root
    group: root
    mode: 0755

- name: munin yum script is symlinked to /etc/munin/plugins
  file:
    src: /usr/local/munin/lib/plugins/yum
    dest: /etc/munin/plugins/yum
    owner: root
    group: root
    state: link
  notify:
    - restart munin-node
    - run yum update script

- name: munin yum script is in root's crontab
  cron:
    name: "run munin yum update script"
    job: "/usr/local/munin/lib/plugins/yum update"
    user: root
    special_time: daily
