---
- name: base dev packages are installed
  become: true
  apt: update_cache=yes name={{packages}} state=present
  vars:
    packages:
      - git
      - tmux
      - tree
      - util-linux
      - htop
