---
- name: dev packages are installed
  become: true
  apt: update_cache=yes name={{ packages }} state=present
  vars:
    packages:
    - automake
    - cmake
    - g++
    - git
    - make
    - pkg-config

- name: toolchain test repository is added
  become: true
  apt_repository: repo=ppa:ubuntu-toolchain-r/test state=present

- name: gcc/g++ 8 are installed
  become: true
  apt: name={{ packages }} state=present
  vars:
    packages:
      - gcc-8
      - g++-8
