
FROM alpine:3.6

RUN apk add --no-cache nginx supervisor
RUN addgroup -g {{ group.id }} {{ group.name }}
RUN adduser -H -D -G {{ group.name }} -u {{ user.id }} {{ user.name }}
RUN mkdir -p /var/www /var/run/supervisord /var/run/nginx /var/log/nginx /var/log/supervisord
RUN chown -R {{ user.name }}:{{ group.name }} /var/lib/nginx /var/log/nginx /var/run/nginx /var/www

ADD supervisord.conf /etc/supervisord.conf
ADD nginx.conf /etc/nginx/nginx.conf
ADD default.conf /etc/nginx/conf.d/default.conf

VOLUME /var/tmp
VOLUME /var/run
VOLUME /var/log
VOLUME /var/www
VOLUME /tmp

EXPOSE {{ listen_port }}

CMD /usr/bin/supervisord
