---
- name: EPEL repository is present
  yum:
    name: epel-release
    state: present

- name: EPEL GPG key is imported
  rpm_key:
    key: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    state: present

- name: munin is installed
  yum:
    name: munin
    state: installed

- name: python-passlib is installed
  yum:
    name: python-passlib
    state: installed

- name: httpd is installed
  yum:
    name: httpd
    state: installed

- name: httpd is enabled and running
  service:
    name: httpd
    state: running
    enabled: yes

- name: munin-node is enabled and running
  service:
    name: munin-node
    state: running
    enabled: yes

- name: munin configuration is installed
  template:
    src: munin.conf.j2
    dest: /etc/munin/munin.conf
    owner: root
    group: root
    mode: 0644

- name: munin user is created
  htpasswd:
    create: yes
    name: "{{ munin_admin_user }}"
    password: "{{ munin_admin_password }}"
    path: /etc/munin/munin-htpasswd
    state: present

- name: munin cron job is running
  lineinfile:
    dest: /etc/cron.d/munin
    state: present
    regexp: "^\\*/5 \\* \\* \\* \\*"
    line: "*/5 * * * *     munin test -x /usr/bin/munin-cron && /usr/bin/munin-cron"

- name: create munin 3rd party plugin directory
  file:
    path: /usr/local/munin/lib/plugins
    owner: root
    group: root
    mode: 0755
    state: directory
    recurse: yes

- name: munin yum script is installed
  copy:
    src: yum
    dest: /usr/local/munin/lib/plugins
    owner: root
    group: root
    mode: 0755
  tags:
    - dev

- name: munin yum script is symlinked to /etc/munin/plugins
  file:
    src: /usr/local/munin/lib/plugins/yum
    dest: /etc/munin/plugins/yum
    owner: root
    group: root
    state: link
  notify: restart munin-node

- name: munin yum script is in root's crontab
  cron:
    name: "run munin yum update script"
    job: "/usr/local/munin/lib/plugins/yum update"
    user: root
    special_time: daily
