---
- name: EPEL repository is present
  yum:
    name: epel-release
    state: present

- name: EPEL GPG key is imported
  rpm_key:
    key: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    state: present

- name: munin is installed
  yum:
    name: munin
    state: installed

- name: python-passlib is installed
  yum:
    name: python-passlib
    state: installed

- name: nginx is installed
  yum:
    name: nginx
    state: installed

- name: nginx is configured
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: reload nginx
    
- name: munin-node is enabled and running
  service:
    name: munin-node
    state: running
    enabled: yes

- name: munin configuration is installed
  template:
    src: munin.conf.j2
    dest: /etc/munin/munin.conf
    owner: root
    group: root
    mode: 0644

- name: munin web user is created
  htpasswd:
    create: yes
    name: "{{ web_user }}"
    password: "{{ web_password }}"
    path: /etc/munin/munin-htpasswd
    state: present

- name: munin cron job is running
  lineinfile:
    dest: /etc/cron.d/munin
    state: present
    regexp: "^\\*/5 \\* \\* \\* \\*"
    line: "*/5 * * * *     munin test -x /usr/bin/munin-cron && /usr/bin/munin-cron"
