---
- name: policycoreutils-python is installed
  yum:
    name: policycoreutils-python
    state: present

- name: selinux is enforcing
  selinux:
    policy: targeted
    state: enforcing

- name: logwatch - is installed
  yum:
    name: logwatch
    state: installed

- include_tasks: sshd.yml

- include_tasks: time.yml

- include_tasks: mail.yml

- include_tasks: cron.yml

- include_tasks: tools.yml
