---
- name: update apt cache
  apt:
    update_cache: yes

- name: install dependencies
  apt: name={{item}} state=installed
  with_items:
    - automake
    - cmake
    - g++
    - git
    - pkg-config
    - tmux
    - tree

- name: dotfiles - repository is checked out
  git:
    repo: https://github.com/olivermichel/dotfiles.git
    dest: /home/{{user_name}}/.dotfiles

- name: dotfiles - include bash configuration
  blockinfile:
    dest: /home/{{user_name}}/.bashrc
    block: |
      . ~/.dotfiles/sh/common.sh
      . ~/.dotfiles/sh/linux.sh
      . ~/.dotfiles/sh/bash/config.bash
      . ~/.dotfiles/sh/bash/prompt-min.bash

- name: dotfiles - link tmux.conf
  file:
    src: /home/{{user_name}}/.dotfiles/tmux.conf
    dest: /home/{{user_name}}/.tmux.conf
    state: link
